# Generated by Django 4.2.23 on 2025-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Комплектация'),
        ),
    ]
