# Generated by Django 4.2.23 on 2025-08-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_discount_product_is_new_product_old_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('profile', 'product')},
        ),
    ]
